spring:
  application:
    name: ecommerce
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/ecommerce

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db.changelog-master.yaml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger

server:
  port: 8888
